### ISSUE TITLE
Inject a dependency in webhook handler

### ISSUE THREAD

**Issue by wolffparkinson** [louis70109/fastapi-line-bot-example#1]
I have a similar project structure for a Chatbot in FastAPI.
How would one approach to implement a dependency injection in the webhook handler for injecting SQLAlchemy session ?

I injected the SQLAlchemy session into the POST request, but then after that to pass it onto the various handlers got me stuck.

One crude approach would be add an optional argument of db session to the Base class of Handler, is there any other way ?

Thank you :))

```python
router = APIRouter()
handler = WebhookHandler(settings.LINE_CHANNEL_SECRET)

@router.post("/")
def handle_line_webhook(
        request: Request, 
        db: Session = Depends(deps.get_db),
		signature: str = Header(None, alias="X-Line-Signature")
):
    # get request body as text
    body = request.body()
    body = body.decode()

    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError as e:
        print(
                "Invalid signature. Please check your channel access token/channel secret."
        )
        raise e

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event: MessageEvent):
    print('msg received')
```

**Comment by louis70109** [comment]
Hi @Tumornator ,
From my experience, maybe you need to init DB session when framework start.

You could reference my another repo -> https://github.com/louis70109/PLeagueBot/blob/master/api.py#L27

Although this project crawlers were un-updated XD

But the DB session parts you could use it.

Thank you :)

**Comment by wolffparkinson** [comment]
Thanks @louis70109 for the quick reply. Yes I have initialized the DB connection in the main app router
```python
root_router = APIRouter()
app = FastAPI(title="Test Alerts - LINE", openapi_url="/openapi.json")

@root_router.on_event("startup")
async def on_startup():
    async with engine_async.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


@root_router.get("/", status_code=200)
async def root() -> str:
    """
    Root GET
    """
    return "OK"


@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response


app.include_router(api_router, prefix=settings.API_V1_STR)
app.include_router(root_router)
```

Thanks for the link to that repo. Really helpful.
Figured out you are using global sessions instance in each module which requires database call.

Just a side note : A global session approach viable for a async approach to database calls with FastAPI ?

P.S. : I was able to figure out how to create a SessionLocal for each request and inject it into each ``@handler`` but  eventually found out that Synchronous SQLAlchemy + FastAPI, runs into issues with multiple incoming concurrent requests while using synchronous session approach on a async platform, which is documented  here :
- [Using dependency injection to get SQLAlchemy session can lead to deadlock](https://github.com/tiangolo/fastapi/issues/3205)
- [sqlalchemy queue pool limit lockup/timeout](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/104#issue-556642895)
- [benchmark between sync and async way using SQLAlchemy and FastAPI](https://github.com/andersonrocha0/fastApiAndSqlAlchemySyncVsAsync)

This was my previous approach where I created a contextvar for the database session and could call the session by context wherever required.
```python
from app.db.session import SessionLocal
from sqlalchemy.orm import Session

def get_db() -> Generator:
    db = SessionLocal()
    db.current_user_id = None
    try:
        yield db
    finally:
        db.close()
        
db_session: ContextVar[Session] = ContextVar('db_session')
```
And calling it in other necessary places like so
```python
from app.api import deps

db = deps.db_session.get()
```
Though this approach, which is similar in sense to the one in PLeague Bot, works fine when the calls are limited, but when it scales, synchronous calls to the database, especially with a big database costs a lot of latency.

I m currently porting all the DB calls to async calls using SQLAlchemy 1.4 via an async session and have left the Dependency injection approach.
Thank you for the reference to PLeague Bot, helps clear a lot of other things too. :))

**Comment by louis70109** [comment]
WoW your explanation so clarify!

If any suggestions please feel free to let me know. (Or some repository)

Thanks again @Tumornator  and hope you have happy coding

**Comment by louis70109** [comment]
@Tumornator 

> Just a side note : A global session approach viable for a async approach to database calls with FastAPI ?

This part I am not sure because my FastAPI integrates experience not more ... orz


```
from app.db.session import SessionLocal
from sqlalchemy.orm import Session

def get_db() -> Generator:
    db = SessionLocal()
    db.current_user_id = None
    try:
        yield db
    finally:
        db.close()
        
db_session: ContextVar[Session] = ContextVar('db_session')
```

This part I had try but I fail on it.
If you have some example repo I can reference it~~ :)
